FROM registry.access.redhat.com/ubi9/ubi

RUN    dnf makecache \
    && dnf install -y java-17-openjdk

# https://access.redhat.com/documentation/en-us/openjdk/17/pdf/using_alt-java/openjdk-17-using_alt-java-en-us.pdf

# To install javac and jaotc install package java-17-openjdk-devel
