FROM redhat/ubi8:8.5

RUN    dnf makecache \
    && dnf install -y java-11-openjdk

# https://access.redhat.com/documentation/en-us/openjdk/11/pdf/using_alt-java/openjdk-11-using_alt-java-en-us.pdf

# To install javac and jaotc install package java-11-openjdk-devel
